version: "3.8"

x-common-variables: &common-variables
  MYSQL_USER: scrapper
  MYSQL_PASSWORD: 12345
  MYSQL_DATABASE: scrappy
  MYSQL_PORT: 3306
  REACT_APP_SERVER_PORT: 8000
  JWT_SECRET: 6867791c0dde7f13ee986df9e8a69ddae53070c60972c6744605884fa65f4a972a797638e80455c74

services:
  mysql-db:
    platform: linux/x86_64
    image: mysql/mysql-server:8.0.23
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  server:
    platform: linux/x86_64
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /server/node_modules/
    links:
      - mysql-db
    command: npm start
  client:
    platform: linux/x86_64
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start